name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup CRuby
      uses: ruby/setup-ruby@v1.66.0
      with:
        ruby-version: 3.0.0
    - name: Setup mruby
      run: sudo apt install mruby=2.0.0-1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: make
      run: make host_production
    - name: make check
      run: make check
